name: Lint Code Base

on:
    push:
        branches:
            - linter-workflow

    pull_request:
        branches: [linter-workflow]

    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: yarn setupc
              run: npm install --global yarn

            - name: install
              run: yarn install

            - name: ESLint
              run: yarn run lint:fix
