name: Lint Code Base

on:
    push:
        branches:
            - linter-workflow

    pull_request:
        branches: [linter-workflow]

    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: yarn setup
              run: npm install --global yarn

            - name: install all dependencies
              run: yarn install

            - name: ESLint
              run: yarn run lint:fix

            - name: Prettier Check
              run: prettier --check .
