name: Lint Code Base

on:
    push:
        branches-ignore: [linter-workflow]

    pull_request:
        branches: [linter-workflow]

jobs:
    build:
        name: Lint Code Base
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: read
            statuses: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Lint Code Base
              uses: github/super-linter@v5
              env:
                  VALIDATE_ALL_CODEBASE: true
                  DEFAULT_BRANCH: master
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
