name: Lint Code Base

on:
    pull_request:
        branches: [master]

    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: "yarn"
                  cache-dependency-path: yarn.lock

            - name: yarn setup
              run: npm install --global yarn

            - name: install all dependencies
              run: yarn install --frozen-lockfile

            - name: ESLint
              run: yarn run lint

            - name: Prettier Check
              run: yarn prettier -c .
