name: Sync Production Branch

on:
    push:
        branches:
            - production

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: production
                  repository: pwd-edu/iabooks-frontend

            - name: Add forked repository remote
              run: git remote add fork https://github.com/Mohamed-Ibrahim-01/iabooks-frontend.git

            - name: Push changes to forked repository
              uses: ad-m/github-push-action@master
              with:
                  branch: production
                  github_token: ${{ secrets.IBRAHIM_FRONTEND_GITHUB_TOKEN }}
                  repository: Mohamed-Ibrahim-01/iabooks-frontend
                  force: true
